-- Supabase SQL schema for "جرد وحسابات المحل"
-- Creates the reference system_items, live inventory_products, and customer_accounts tables
-- and enables permissive Row-Level Security policies for simple public access (adjust for production).

-- 1. جدول أصناف السيستم والمخزون المرجعي
CREATE TABLE IF NOT EXISTS system_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    normalized_name TEXT UNIQUE,
    system_qty NUMERIC DEFAULT 0,
    unit_price NUMERIC DEFAULT 0, -- سعر البيع الافتراضي
    barcode TEXT,
    category TEXT DEFAULT 'عام',
    inventory_id BIGINT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 2. جدول أصناف الجرد الفعلي والحصر الحي
CREATE TABLE IF NOT EXISTS inventory_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    quantities JSONB DEFAULT '[]'::jsonb, -- مصفوفة الأعداد المدخلة (مثلاً [5, 10, 3])
    total_quantity NUMERIC DEFAULT 0,
    unit_price NUMERIC DEFAULT 0,
    barcode TEXT,
    inventory_id BIGINT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 3. جدول حسابات العملاء والموردين (عليا كام / ليا كام)
CREATE TABLE IF NOT EXISTS customer_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('receivable', 'payable')), -- receivable = ليا (مدين) / payable = عليا (دائن)
    amount NUMERIC DEFAULT 0,
    is_included BOOLEAN DEFAULT true, -- لتضمين/استبعاد الشخص من الحسبة بدون حذفه
    phone TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- تفعيل الصلاحيات للجميع
ALTER TABLE system_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for system_items" ON system_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for inventory_products" ON inventory_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for customer_accounts" ON customer_accounts FOR ALL USING (true) WITH CHECK (true);

-- Optional: index helpers (normalized_name lookup)
CREATE INDEX IF NOT EXISTS idx_system_items_normalized_name ON system_items (normalized_name);
CREATE INDEX IF NOT EXISTS idx_inventory_products_name ON inventory_products (LOWER(name));

-- Notes:
-- 1) These RLS policies are permissive (allow all). For production, restrict using auth.uid() or other claims.
-- 2) Run this script in the Supabase SQL editor or psql connected to your Supabase Postgres instance.
-- 3) If you want, I can also add database triggers to keep normalized_name in sync, or a migration script.
