-- Fekra Inventory: durable inventory sessions
-- Run this migration in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.inventory_sessions (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'جرد جديد',
  status text not null default 'draft' check (status in ('draft','completed','archived')),
  comparison_scope text not null default 'partial' check (comparison_scope in ('partial','full')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.inventory_counts (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.inventory_sessions(id) on delete cascade,
  product_name text not null,
  normalized_name text not null,
  barcode text not null default '',
  quantities jsonb not null default '[]'::jsonb,
  total_quantity numeric not null default 0 check (total_quantity >= 0),
  unit_price numeric not null default 0 check (unit_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(session_id, normalized_name)
);

create index if not exists inventory_counts_session_idx on public.inventory_counts(session_id);
create index if not exists inventory_counts_name_idx on public.inventory_counts(normalized_name);

create or replace function public.touch_inventory_session()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists inventory_sessions_touch on public.inventory_sessions;
create trigger inventory_sessions_touch before update on public.inventory_sessions
for each row execute function public.touch_inventory_session();

create or replace function public.touch_inventory_count()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists inventory_counts_touch on public.inventory_counts;
create trigger inventory_counts_touch before update on public.inventory_counts
for each row execute function public.touch_inventory_count();

alter table public.inventory_sessions enable row level security;
alter table public.inventory_counts enable row level security;

-- Development-compatible policies for the current single-store app.
-- Replace these with auth.uid()-scoped policies when multi-user roles are enabled.
drop policy if exists inventory_sessions_public_access on public.inventory_sessions;
create policy inventory_sessions_public_access on public.inventory_sessions
for all using (true) with check (true);

drop policy if exists inventory_counts_public_access on public.inventory_counts;
create policy inventory_counts_public_access on public.inventory_counts
for all using (true) with check (true);
